version: '3.5'

services:
  backend:
    build: .
    ports:
      - 8080:8080
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DBNAME: ${DB_DBNAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
    tty: true
    env_file: [.env]
    depends_on:
      - database
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DBNAME}
    ports:
      - 3306:3306
    volumes:
      - my_db:/var/lib/mysql
    env_file: [ .env ]
volumes:
  my_db:

